# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:


services:
    authentication_handler:
        class:        AppBundle\Handler\AuthenticationHandler
        arguments:    ["@router", "@fos_user.user_manager", "@service_container", "@translator"]
    my_user_provider:
        class: AppBundle\Security\UserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager",{facebook: facebook_id, google: google_id, twitter: twitter_id}]

twig:
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"